import 'package:cloud_firestore/cloud_firestore.dart';

class DatabaseSeeder {
  static Future<void> seedAlerts() async {
    final CollectionReference alerts = FirebaseFirestore.instance.collection('alerts');

    final List<Map<String, dynamic>> dummyAlerts = [
      // 30 Nationwide Alerts (Each from a different city)
      {
        'title': 'Heavy Rainfall Warning',
        'district': 'Mumbai',
        'location': const GeoPoint(19.0760, 72.8777),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Severe waterlogging expected in low-lying areas. Avoid travel near Hindmata.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Air Quality Emergency',
        'district': 'Delhi',
        'location': const GeoPoint(28.6139, 77.2090),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'AQI has crossed 450. Use N95 masks. Schools closed.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Flash Flood Alert',
        'district': 'Bangalore',
        'location': const GeoPoint(12.9716, 77.5946),
        'isOfficial': false,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Heavy rains causing flooding in Bellandur. Commuters stuck.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Cyclone Update',
        'district': 'Chennai',
        'location': const GeoPoint(13.0827, 80.2707),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Rescue',
        'createdBy': 'system_admin',
        'description': 'Coastal evacuation in progress. Stay away from Marina beach.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Storm Surge Warning',
        'district': 'Kolkata',
        'location': const GeoPoint(22.5726, 88.3639),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'River levels rising in Howrah area.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Heatwave Advisory',
        'district': 'Hyderabad',
        'location': const GeoPoint(17.3850, 78.4867),
        'isOfficial': true,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'Medical',
        'createdBy': 'system_admin',
        'description': 'Temperatures to touch 45°C. Stay hydrated.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Landslide Blockage',
        'district': 'Pune',
        'location': const GeoPoint(18.5204, 73.8567),
        'isOfficial': false,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Rescue',
        'createdBy': 'system_admin',
        'description': 'Landslide on Tamhini Ghat. Road blocked.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Industrial Fire',
        'district': 'Ahmedabad',
        'location': const GeoPoint(23.0225, 72.5714),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Fire',
        'createdBy': 'system_admin',
        'description': 'Major fire at Vatva GIDC. Fire tenders on spot.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Dust Storm Warning',
        'district': 'Jaipur',
        'location': const GeoPoint(26.9124, 75.7873),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Strong winds and low visibility expected.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Urban Flooding',
        'district': 'Lucknow',
        'location': const GeoPoint(26.8467, 80.9462),
        'isOfficial': false,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Hazratganj roads underwater.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Chemical Leak',
        'district': 'Kanpur',
        'location': const GeoPoint(26.4499, 80.3319),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Medical',
        'createdBy': 'system_admin',
        'description': 'Ammonia leak reported near Panki. Evacuation started.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Medical Emergency Cluster',
        'district': 'Nagpur',
        'location': const GeoPoint(21.1458, 79.0882),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Medical',
        'createdBy': 'system_admin',
        'description': 'Spike in heat stroke cases.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Drainage Crisis',
        'district': 'Indore',
        'location': const GeoPoint(22.7196, 75.8577),
        'isOfficial': false,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Blocked drainage in Vijay Nagar.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Building Risk',
        'district': 'Thane',
        'location': const GeoPoint(19.2183, 72.9781),
        'isOfficial': true,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Rescue',
        'createdBy': 'system_admin',
        'description': 'Building in Mumbra showing cracks.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Gas Pipeline Work',
        'district': 'Bhopal',
        'location': const GeoPoint(23.2599, 77.4126),
        'isOfficial': true,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Maintenance work ongoing.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Coastal Alert',
        'district': 'Visakhapatnam',
        'location': const GeoPoint(17.6868, 83.2185),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Rescue',
        'createdBy': 'system_admin',
        'description': 'Strong waves damaging RK Beach road.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Safety Drill',
        'district': 'Surat',
        'location': const GeoPoint(21.1702, 72.8311),
        'isOfficial': true,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Mock drill at city hospital.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'River Danger Mark',
        'district': 'Patna',
        'location': const GeoPoint(25.5941, 85.1376),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Ganga river nearing danger mark.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Flood Update',
        'district': 'Vadodara',
        'location': const GeoPoint(22.3072, 73.1812),
        'isOfficial': false,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Vishwamitri river overflowed.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Pollution Alert',
        'district': 'Ghaziabad',
        'location': const GeoPoint(28.6692, 77.4538),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Dust from construction sites.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Factory Fire',
        'district': 'Ludhiana',
        'location': const GeoPoint(30.9010, 75.8573),
        'isOfficial': false,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Fire',
        'createdBy': 'system_admin',
        'description': 'Major fire in industrial area.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Forest Smoke',
        'district': 'Coimbatore',
        'location': const GeoPoint(11.0168, 76.9558),
        'isOfficial': true,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Smoke drifting from Western Ghats.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Tourist Footfall',
        'district': 'Agra',
        'location': const GeoPoint(27.1767, 78.0081),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Logistics',
        'createdBy': 'system_admin',
        'description': 'High tourist footfall at Taj Mahal.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Festival Crowd',
        'district': 'Madurai',
        'location': const GeoPoint(9.9252, 78.1198),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Logistics',
        'createdBy': 'system_admin',
        'description': 'Large gathering at Meenakshi Temple.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Traffic Diversion',
        'district': 'Nashik',
        'location': const GeoPoint(19.9975, 73.7898),
        'isOfficial': true,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'Logistics',
        'createdBy': 'system_admin',
        'description': 'Traffic diversions near Panchavati.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Power Failure',
        'district': 'Faridabad',
        'location': const GeoPoint(28.4089, 77.3178),
        'isOfficial': false,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Major transformer blast.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Security Precaution',
        'district': 'Meerut',
        'location': const GeoPoint(28.9845, 77.7064),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Section 144 imposed in sensitive areas.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Water Pipe Leak',
        'district': 'Rajkot',
        'location': const GeoPoint(22.3039, 70.8022),
        'isOfficial': false,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'General',
        'createdBy': 'system_admin',
        'description': 'Major leak near Kalavad Road.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Train Delay',
        'district': 'Kalyan',
        'location': const GeoPoint(19.2403, 73.1305),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Logistics',
        'createdBy': 'system_admin',
        'description': 'Overhead wire snap.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Inundation Warning',
        'district': 'Vasai',
        'location': const GeoPoint(19.3917, 72.8397),
        'isOfficial': true,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Flood',
        'createdBy': 'system_admin',
        'description': 'Sea water entering coastal villages.',
        'timestamp': FieldValue.serverTimestamp(),
      },

      // 6 Alerts from Navi Mumbai (Mixture of Public & Personal)
      {
        'title': 'Palm Beach Accident',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0185, 73.0180),
        'isOfficial': false,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'public',
        'type': 'Rescue',
        'createdBy': 'system_admin',
        'description': 'Multi-vehicle collision near Sanpada.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Station Rush',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0645, 72.9983),
        'isOfficial': false,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'public',
        'type': 'Logistics',
        'createdBy': 'system_admin',
        'description': 'Heavy rush on Vashi Platform 1.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Medical Help Required',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0330, 73.0297),
        'isOfficial': false,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'personal',
        'type': 'Medical',
        'createdBy': 'citizen_user_1',
        'description': 'Elderly citizen needs urgent first aid help at home in Belapur.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Heavy Lifting Needed',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0750, 73.0000),
        'isOfficial': false,
        'severity': 'Info',
        'status': 'active',
        'visibility': 'personal',
        'type': 'Physical',
        'createdBy': 'citizen_user_2',
        'description': 'Need help moving furniture for a disabled resident in Vashi.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Belapur Hills Fire',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0204, 73.0416),
        'isOfficial': false,
        'severity': 'Critical',
        'status': 'active',
        'visibility': 'public',
        'type': 'Fire',
        'createdBy': 'system_admin',
        'description': 'Dry grass fire behind CBD Belapur.',
        'timestamp': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Medical Check-up Assistance',
        'district': 'Navi Mumbai',
        'location': const GeoPoint(19.0400, 73.0200),
        'isOfficial': false,
        'severity': 'Warning',
        'status': 'active',
        'visibility': 'personal',
        'type': 'Medical',
        'createdBy': 'citizen_user_3',
        'description': 'Need a medical volunteer to help monitor vitals for a patient in Nerul.',
        'timestamp': FieldValue.serverTimestamp(),
      },
    ];

    for (var data in dummyAlerts) {
      await alerts.add(data);
    }
    print('Successfully seeded ${dummyAlerts.length} alerts with full schema!');
  }
}
