import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedData() async {
  final CollectionReference alerts = FirebaseFirestore.instance.collection('alerts');
  const String adminId = 'QyeGVd1w4lNWjOBF6tfkVwOAx512';

  final List<Map<String, dynamic>> dummyAlerts = [
    // 5 Navi Mumbai Alerts
    {
      'title': 'Severe Heatwave',
      'description': 'Extreme temperatures expected in Vashi and Belapur. Stay hydrated.',
      'district': 'Navi Mumbai',
      'severity': 'Critical',
      'location': const GeoPoint(19.0330, 73.0297),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Water Supply Disruption',
      'description': 'Maintenance work in Nerul and Seawoods. Plan accordingly.',
      'district': 'Navi Mumbai',
      'severity': 'Medium',
      'location': const GeoPoint(19.0330, 73.0197),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'High Tide Warning',
      'description': 'High tide expected along Palm Beach Road. Avoid coastal areas.',
      'district': 'Navi Mumbai',
      'severity': 'Warning',
      'location': const GeoPoint(19.0200, 73.0100),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Industrial Smoke Alert',
      'description': 'Low visibility in Kopar Khairane due to industrial haze.',
      'district': 'Navi Mumbai',
      'severity': 'Medium',
      'location': const GeoPoint(19.0900, 73.0100),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Traffic Congestion',
      'description': 'Heavy traffic on Sion-Panvel Highway near Kharghar.',
      'district': 'Navi Mumbai',
      'severity': 'Info',
      'location': const GeoPoint(19.0250, 73.0550),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },

    // 35+ Alerts from Different Cities
    {
      'title': 'Urban Flooding',
      'description': 'Andheri Subway closed due to waterlogging.',
      'district': 'Mumbai',
      'severity': 'Critical',
      'location': const GeoPoint(19.1136, 72.8697),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Smog Emergency',
      'description': 'AQI > 500. Schools closed for 2 days.',
      'district': 'Delhi',
      'severity': 'Critical',
      'location': const GeoPoint(28.6139, 77.2090),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Flash Floods',
      'description': 'Heavy rains in Bellandur. Risk of overflow.',
      'district': 'Bengaluru',
      'severity': 'High',
      'location': const GeoPoint(12.9716, 77.5946),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Cyclone Warning',
      'description': 'Cyclone approaching East Coast. Evacuation starting.',
      'district': 'Chennai',
      'severity': 'Critical',
      'location': const GeoPoint(13.0827, 80.2707),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Heavy Thunderstorms',
      'description': 'Lightning strikes reported. Stay indoors.',
      'district': 'Kolkata',
      'severity': 'Warning',
      'location': const GeoPoint(22.5726, 88.3639),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Heatwave Red Alert',
      'description': 'Temps crossing 48C. Avoid outdoor work.',
      'district': 'Hyderabad',
      'severity': 'Critical',
      'location': const GeoPoint(17.3850, 78.4867),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Landslide Alert',
      'description': 'Lonavala ghats closed due to boulder falls.',
      'district': 'Pune',
      'severity': 'High',
      'location': const GeoPoint(18.5204, 73.8567),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Dust Storm',
      'description': 'Severe dust storm expected within 2 hours.',
      'district': 'Ahmedabad',
      'severity': 'Warning',
      'location': const GeoPoint(23.0225, 72.5714),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'River Overflow',
      'description': 'Tapi river level rising. Low lying areas alert.',
      'district': 'Surat',
      'severity': 'High',
      'location': const GeoPoint(21.1702, 72.8311),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Cold Wave Warning',
      'description': 'Frost expected. Protect livestock.',
      'district': 'Jaipur',
      'severity': 'Medium',
      'location': const GeoPoint(26.9124, 75.7873),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Dengue Outbreak',
      'description': 'High cases in Gomti Nagar. Fumigation active.',
      'district': 'Lucknow',
      'severity': 'Warning',
      'location': const GeoPoint(26.8467, 80.9462),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Industrial Gas Leak',
      'description': 'Minor leak detected in Panki area. No need to panic.',
      'district': 'Kanpur',
      'severity': 'Medium',
      'location': const GeoPoint(26.4499, 80.3319),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Unseasonal Hailstorm',
      'description': 'Crop damage risk. Seek shelter.',
      'district': 'Nagpur',
      'severity': 'High',
      'location': const GeoPoint(21.1458, 79.0882),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Traffic Gridlock',
      'description': 'Major accident on AB Road. Traffic diverted.',
      'district': 'Indore',
      'severity': 'Info',
      'location': const GeoPoint(22.7196, 75.8577),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Building Collapse Risk',
      'description': 'Dilapidated building evacuated in Naupada.',
      'district': 'Thane',
      'severity': 'High',
      'location': const GeoPoint(19.2183, 72.9781),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Forest Fire Alert',
      'description': 'Fire detected in nearby hills. Air quality impacted.',
      'district': 'Bhopal',
      'severity': 'Warning',
      'location': const GeoPoint(23.2599, 77.4126),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Coastal Erosion',
      'description': 'Strong waves damaging RK Beach promenade.',
      'district': 'Visakhapatnam',
      'severity': 'Medium',
      'location': const GeoPoint(17.6868, 83.2185),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Mosquito Borne Illness',
      'description': 'Increase in malaria cases. Use repellents.',
      'district': 'Patna',
      'severity': 'Medium',
      'location': const GeoPoint(25.5941, 85.1376),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Power Grid Failure',
      'description': 'Partial blackout in Sayajigunj. Restoration in progress.',
      'district': 'Vadodara',
      'severity': 'Medium',
      'location': const GeoPoint(22.3072, 73.1812),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Pollution Spike',
      'description': 'Industrial exhaust limits exceeded in Loni.',
      'district': 'Ghaziabad',
      'severity': 'Warning',
      'location': const GeoPoint(28.6692, 77.4538),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Bridge Inspection',
      'description': 'Old canal bridge closed for safety check.',
      'district': 'Ludhiana',
      'severity': 'Info',
      'location': const GeoPoint(30.9010, 75.8573),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Fog Red Alert',
      'description': 'Zero visibility on Yamuna Expressway.',
      'district': 'Agra',
      'severity': 'Critical',
      'location': const GeoPoint(27.1767, 78.0081),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Wine Festival Traffic',
      'description': 'Heavy congestion near Sula Vineyards.',
      'district': 'Nashik',
      'severity': 'Info',
      'location': const GeoPoint(19.9975, 73.7898),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Metro Construction Hazard',
      'description': 'Crane instability reported near Sector 12.',
      'district': 'Faridabad',
      'severity': 'High',
      'location': const GeoPoint(28.4089, 77.3178),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Public Rally Alert',
      'description': 'Massive gathering near Clock Tower. Diversions active.',
      'district': 'Meerut',
      'severity': 'Info',
      'location': const GeoPoint(28.9845, 77.7064),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Salt Pan Encroachment',
      'description': 'Tidal flow affected in Vasai east.',
      'district': 'Vasai-Virar',
      'severity': 'Medium',
      'location': const GeoPoint(19.3919, 72.8397),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Ganga Level Warning',
      'description': 'Assi Ghat partially submerged due to rain.',
      'district': 'Varanasi',
      'severity': 'Warning',
      'location': const GeoPoint(25.3176, 82.9739),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Snowfall Blockade',
      'description': 'NH44 blocked near Jawahar Tunnel.',
      'district': 'Srinagar',
      'severity': 'High',
      'location': const GeoPoint(34.0837, 74.7973),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Caves Maintenance',
      'description': 'Tourist entry restricted due to loose rocks.',
      'district': 'Aurangabad',
      'severity': 'Medium',
      'location': const GeoPoint(19.8762, 75.3433),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Coal Mine Fire Haze',
      'description': 'Sulfurous smell reported in Jharia.',
      'district': 'Dhanbad',
      'severity': 'Warning',
      'location': const GeoPoint(23.7957, 86.4304),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Airport Runway Closure',
      'description': 'Temporary closure due to technical issue.',
      'district': 'Coimbatore',
      'severity': 'High',
      'location': const GeoPoint(11.0168, 76.9558),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Port Storm Signal 2',
      'description': 'Vessels advised to remain in harbour.',
      'district': 'Kochi',
      'severity': 'Warning',
      'location': const GeoPoint(9.9312, 76.2673),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Beach Safety Alert',
      'description': 'Strong rip currents at Miramar. No swimming.',
      'district': 'Goa',
      'severity': 'High',
      'location': const GeoPoint(15.4909, 73.8278),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Golden Temple Roadwork',
      'description': 'Strict traffic control in Hall Gate area.',
      'district': 'Amritsar',
      'severity': 'Info',
      'location': const GeoPoint(31.6340, 74.8723),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
    {
      'title': 'Wild Elephant Sighting',
      'description': 'Tuskers spotted near village borders. Caution.',
      'district': 'Mysuru',
      'severity': 'Warning',
      'location': const GeoPoint(12.2958, 76.6394),
      'isOfficial': true,
      'createdBy': adminId,
      'engagedBy': null,
      'status': 'active',
      'type': 'General',
      'visibility': 'public',
      'ai_actions': null,
      'timestamp': Timestamp.now(),
    },
  ];

  for (var alert in dummyAlerts) {
    await alerts.add(alert);
  }
  print("✅ 40+ Emergency Scenarios Seeded by Admin with correct fields!");
}
